<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo ASSET_SAYA ?>surat/style3.css" />
    <title>Laporan Transaksi</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<!--<img width="400" src="<?php echo ASSET_SAYA ?>/travelium/img/icon_hotelgarudawira.png" />-->
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
					<center>
						<p style="font-weight:none;font-size:12pt">LAPORAN DATA TRANSAKSI</br>
						Periode : <?php echo date("d F Y",strtotime($tgl1));?> s/d <?php echo date("d F Y",strtotime($tgl2));?></p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td>No</th>
							<td style="text-align:left;"> &nbsp;No. Transaksi</td>
							<td style="text-align:left;"> &nbsp;Tgl. Transaksi</td>
							<td style="text-align:left;"> &nbsp;Atas Nama</td>
							<td style="text-align:right;">Tarif &nbsp;</td>
							<td style="text-align:right;">Tarif Tambahan &nbsp;</td>
							<td style="text-align:right;">Total Tarif &nbsp;</td>
							<td style="text-align:right;">Total Biaya Operasional &nbsp;</td>
							<td style="text-align:right;">Total Keuntungan &nbsp;</td>
						</tr>
						<?php  
						$total_harga_default = 0;
						$total_biaya_tambahan = 0;
						$total_harga = 0;
						$total_biaya_operasional = 0;
						$total_keuntungan = 0;
						$no = 0;
						foreach($listData as $value){
							$total_harga_default = $total_harga_default + $value['total_harga_default'];
							$total_biaya_tambahan = $total_biaya_tambahan + $value['total_biaya_tambahan'];
							$total_harga = $total_harga + $value['total_harga'];
							$total_biaya_operasional = $total_biaya_operasional + $value['total_biaya_operasional'];
							$total_keuntungan = $total_keuntungan + $value['total_keuntungan'];
							$no++;
						 ?>
						<tr class="isi-colom">
							<td style="font-size:8pt;"> &nbsp;<?php echo $no;?></td>
							<td style="font-size:8pt; text-align:left;"> &nbsp;<?php echo $value['transaksi_id'] ?></td>
							<td style="font-size:8pt; text-align:left;"> &nbsp;<?php echo date("d F Y",strtotime($value['tanggal_transaksi'])); ?></td>
							<td style="font-size:8pt; text-align:left;"> &nbsp;<?php echo $value['nama_pelanggan']; ?></td>
							<td style="font-size:8pt; text-align:right;"><?php echo "Rp. ".number_format($value['total_harga_default'],0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt; text-align:right;"><?php echo "Rp. ".number_format($value['total_biaya_tambahan'],0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt; text-align:right;"><?php echo "Rp. ".number_format($value['total_harga'],0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt; text-align:right;"><?php echo "Rp. ".number_format($value['total_biaya_operasional'],0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt; text-align:right;"><?php echo "Rp. ".number_format($value['total_keuntungan'],0,'.','.'); ?> &nbsp;</td>
						</tr>
                        <?php } ?>
						<tr class="isi-colom">
							<td style="font-size:8pt;text-align:right;"" colspan="3">Total&nbsp;</td>
							<td style="font-size:8pt;text-align:center;" ><?php echo $no;?> Data</td>
							<td style="font-size:8pt;text-align:right;" ><?php echo "Rp. ".number_format($total_harga_default,0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt;text-align:right;" ><?php echo "Rp. ".number_format($total_biaya_tambahan,0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt;text-align:right;" ><?php echo "Rp. ".number_format($total_harga,0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt;text-align:right;" ><?php echo "Rp. ".number_format($total_biaya_operasional,0,'.','.'); ?> &nbsp;</td>
							<td style="font-size:8pt;text-align:right;" ><?php echo "Rp. ".number_format($total_keuntungan,0,'.','.'); ?> &nbsp;</td>
						</tr>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>